PKG_VER=0.4.5
PKG_CATEGORY="Box64"
PKG_PRETTY_NAME="Box64"

GIT_URL=https://github.com/ptitSeb/box64
CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithDebInfo -DANDROID=1 -DBAD_SIGNAL=1 -DARM_DYNAREC=1"
BLACKLIST_ARCH=x86_64
